[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "grow", "--transition-fps", "60", "--transition-pos", "top-right" ]
set = true

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/matugen/outputs/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/matugen/outputs/kitty-colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-dark'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.rofi]
input_path = '~/.config/matugen/templates/colors.rasi'
output_path = '~/.config/matugen/outputs/colors.rasi'

[config]

[templates.mako]
input_path = '~/.config/matugen/templates/mako-colors'
output_path = '~/.config/matugen/outputs/mako-colors'
post_hook = 'makoctl reload'
